export type Category =
  | "africa-capital"
  | "africa-dev"
  | "ai"
  | "inner"
  | "strategy"
  | "money";

export const categoryLabels: Record<Category, string> = {
  "africa-capital": "Africa & Capital",
  "africa-dev": "Africa & Development",
  ai: "AI & Creative Practice",
  inner: "Inner Practice",
  strategy: "Strategy & Decisions",
  money: "Money & Meaning",
};

// Display order on the page — top to bottom.
export const categoryOrder: Category[] = [
  "africa-capital",
  "africa-dev",
  "ai",
  "inner",
  "strategy",
  "money",
];

export type PatternVideo = { title: string; id: string; category: Category };

// Seeded 2026-06-03 from youtube.com/@Sid-Mofya/shorts via browser console snippet.
// Titles have been stripped of leading "NN -" numbers and trailing #hashtags.
// To add a new short: prepend an entry to this array with the right category.
// id = the YouTube video ID — the part after /shorts/ or /watch?v=
export const videos: PatternVideo[] = [
  { title: "If I had to rebuild from nothing, AI would be my cofounder", id: "v2UlrKdu1rU", category: "ai" },
  { title: "What gets you out of bed in the morning It’s not purpose or pressure It’s presence", id: "RialwAst8zg", category: "inner" },
  { title: "Start with silence Not because you’re tired, but because it’s where clarity begin", id: "MnB-1i4JDP4", category: "inner" },
  { title: "When there’s more time than work, what will you do with yourself", id: "8UqXKxwo5Ug", category: "inner" },
  { title: "Play isn’t the opposite of work It’s the purest form of presence", id: "7wFyFupgyeg", category: "inner" },
  { title: "Africa holds the origin story It may also hold the next chapter", id: "5ri0CAqhS1E", category: "africa-dev" },
  { title: "Development isn’t always about going ahead Sometimes it’s about coming home to yourself", id: "gJLFDgpj6jo", category: "inner" },
  { title: "In African culture, to mourn well is to live well", id: "xUAx-NP9Sd0", category: "inner" },
  { title: "In a world obsessed with numbers, don’t forget the real asset is human", id: "wCl4GbGJCkc", category: "money" },
  { title: "Rituals don’t need to be erased They need to be realigned with the pattern", id: "16mUoT9R1lM", category: "inner" },
  { title: "The best ideas don’t always come from you Sometimes they come through you", id: "LyLENmbO_Ig", category: "ai" },
  { title: "The smallest rituals create the deepest bonds", id: "qaSGsr-UY-E", category: "money" },
  { title: "Everyone’s chasing reach I’m chasing resonance", id: "totjncDGp3I", category: "money" },
  { title: "What if simplicity wasn’t a constraint… but a strategy", id: "WU0EZ1PjW1M", category: "strategy" },
  { title: "If you're still treating AI like a typing assistant, you're missing the point", id: "pE-KJ0W70oM", category: "ai" },
  { title: "Before you hire an agency, ask yourself this ONE question", id: "K118F-DwNk8", category: "strategy" },
  { title: "Exploring investment in Africa is like making the perfect cup of tea", id: "KWJssVfkN58", category: "africa-capital" },
  { title: "Burnout isn't just overwork", id: "TN6LIAOgMi8", category: "inner" },
  { title: "Financial freedom isn't just about the end result", id: "B_J5miU3uZA", category: "money" },
  { title: "Unresolved projects can sap our energy", id: "A6UPLeUcE14", category: "inner" },
  { title: "Your time is limited, so don't waste it living someone else's life", id: "EG-vKeIOSdk", category: "money" },
  { title: "Rethink the Problem to Solve it", id: "Uv_o93_MMWk", category: "strategy" },
  { title: "Transform Your Challenges Through a Simplification Strategy", id: "eJSpvC-2BLA", category: "strategy" },
  { title: "Break Challenges Into Manageable Parts to Solve Them", id: "lOc_dza1lWg", category: "strategy" },
  { title: "Unlock smarter problem solving by daring to start from scratch", id: "ytBXksd3FVg", category: "strategy" },
  { title: "The Power Lies in Questioning Our Assumptions", id: "I2XMx-PBQ1A", category: "strategy" },
  { title: "A river of material flows through us when we share our works and our ideas", id: "QVnUOMIGdLg", category: "ai" },
  { title: "The way we do anything is the way we do everything", id: "j92cPSrzWvo", category: "inner" },
  { title: "When We Don't Yet Know Where We Are Going, We Don't Wait, We Move Forward In The Dark", id: "gL692HN2Ml4", category: "inner" },
  { title: "Sometimes The Mistakes Are What Make A Work Great", id: "fwjsBCiGRdc", category: "ai" },
  { title: "Zoom in and obsess, zoom out and observe", id: "fWVxS2izDi8", category: "strategy" },
  { title: "Investing In Emerging Markets Requires A GOOD Exit Strategy", id: "jyOQ98UBg0Q", category: "strategy" },
  { title: "Who You Invest With MATTERS Most in Emerging Markets Investing", id: "KXfXmdBf_Jk", category: "strategy" },
  { title: "Is Your Business Idea a Good Fit for Local Markets", id: "2DJouFw6BCE", category: "strategy" },
  { title: "Protect Your Profits Mastering Currency Hedging in Emerging Markets", id: "SYCfESWXzHE", category: "africa-capital" },
  { title: "What Every Investor Absolutely NEEDS to Know About Emerging Markets", id: "2G8lJcozPr8", category: "strategy" },
  { title: "New Investment Structures are Making Investing into Mining Accessible to More Investors", id: "lxj5GynPjXU", category: "africa-capital" },
  { title: "Mining Promises Venture Style Return", id: "CeAKXhYPGKU", category: "africa-capital" },
  { title: "Strategic Investments Flow into Mining and You Can Participate", id: "iRPK_xMOYKE", category: "africa-capital" },
  { title: "This is What We Can Learn from Mining Companies", id: "mfxsqCnB7Po", category: "strategy" },
  { title: "We Can Not Have a Tech Future Without Investing into the Right Assets", id: "Gkdou1njfyg", category: "strategy" },
  { title: "The Next 20 Years are Critical for Africa's Future", id: "j8jN71JpVf4", category: "africa-dev" },
  { title: "Everyone Wants to Start a Business, Few Build Ones That Last", id: "hv0eOMvdwnk", category: "strategy" },
  { title: "Uncovering Smart Money: These Are The Trends in Africa", id: "a0b5KnQouyI", category: "africa-capital" },
  { title: "Entrepreneurship in Africa is The New Gold", id: "U_xD4B41f6Q", category: "africa-dev" },
  { title: "Africa is Rich, But Who Exactly Owns Its Wealth?", id: "oqCY2xWunHg", category: "africa-capital" },
  { title: "There are Three Kinds of Businesses Forming with AI Right Now", id: "diGucTzXCc4", category: "ai" },
  { title: "Let's Spark Innovation in African Agriculture", id: "-OnAgVnVFPM", category: "africa-dev" },
  { title: "This is Why I'm Investing in Mining in Africa", id: "tpLsg6n99Y4", category: "africa-capital" },
  { title: "Happiness Is Divided Into Two Halves, Accumulating and Letting Go", id: "RL9s08Qn-C4", category: "money" },
  { title: "This is The Difference Between Internal Performance and External Performance", id: "OzkCOJvTs3Y", category: "inner" },
  { title: "From Grid Instability to Powering Millions: The AIIM Story", id: "fLV5mhQPcu0", category: "africa-capital" },
  { title: "Strategic Investments Pay Back, Ask Norfun About the 60 Million Fertilizer Terminal", id: "5Ry47wgKj0k", category: "africa-capital" },
  { title: "Visa's 200 Million Bet was Genious", id: "RQsB4mhkRqc", category: "strategy" },
  { title: "Transforming Waste into Wealth: Let's Learn from Twigga Foods' Revolution", id: "spAqVQgeyCs", category: "africa-capital" },
  { title: "CrossBoundary's Revolutionized The Solar Industry in Africa", id: "--OHQ9OU6do", category: "africa-capital" },
  { title: "Remember, There are Things that Don't Change Even with Technology and AI", id: "fTRATNmZ_vc", category: "inner" },
  { title: "The F-Word is Part of Our Experience", id: "MarZGZuSUjI", category: "inner" },
  { title: "We Have to Embrace Embodied Learning in Our Changing World", id: "dh4-sBqP8qI", category: "ai" },
  { title: "We Have to Relearn When We Move from Digital to AI", id: "qA3I5jUEPSo", category: "ai" },
  { title: "We Need to Unlearn to Work Effectively with AI", id: "hrrnaUVWgFU", category: "ai" },
  { title: "Why You Should Not Just Build Wealth", id: "Uf931DvOMBk", category: "money" },
  { title: "These are the Two Fastest Ways to Build Your Career or Business", id: "gNnS6q4RxX0", category: "money" },
  { title: "Money Or Soul Or Both", id: "QvbQshpCUzs", category: "money" },
  { title: "These are The Two Modes of Creativity that I am Experiencing", id: "JqTvaxDmts0", category: "ai" },
  { title: "Africa's Future Depends on The Small Miners and Farmers", id: "CsMLhWcZBg4", category: "africa-dev" },
  { title: "Legacy is Left in Other People", id: "vTglsd7tAuY", category: "money" },
  { title: "Atomic Essays Make You a Better Communicator", id: "LP_ptnZU_gU", category: "strategy" },
  { title: "I Love Dukas", id: "VtESuSjRE00", category: "africa-dev" },
  { title: "The 3 Ways How I Evaluate Business Opportunities as a VC", id: "MHdocHds2RE", category: "strategy" },
  { title: "Investing in Mining in Africa is One of The Lowest Risk Investments You Can Make", id: "RHKr8erfyMk", category: "africa-capital" },
  { title: "Sometimes Value Comes in Tiny, Tiny Packages", id: "XM3BFqJpUag", category: "money" },
  { title: "Sometimes Value Comes From The Most Unexpected of Places", id: "aqn74flHZys", category: "money" },
  { title: "There are Two Sides of The Coin When Thinking about African Development", id: "dB71veP87rc", category: "africa-dev" },
  { title: "We Can Learn from Bees about Capital", id: "9GxZi16FubU", category: "strategy" },
  { title: "Here is a Way to Think How Bitcoin Promotes its Value as a Currency", id: "BEcFfhHyNHM", category: "strategy" },
  { title: "How I Created a Song Combined with a Story that is Thousands of Years Old", id: "ux0MLPnk-aw", category: "ai" },
  { title: "This is Big Lesson We Can Learn from Kodak", id: "0Xp_2Yu_qrg", category: "strategy" },
  { title: "I Don't Think of Africa as 54 Countries", id: "pJq8NpK6PhI", category: "africa-dev" },
  { title: "Do You Choose to Make Money Or Meaning", id: "2q_o_iNZjy0", category: "money" },
  { title: "These are the Two Things I Learned from Going Home Visiting Zambia", id: "EE1rxuES9Rs", category: "inner" },
  { title: "This is The One Policy I Would Change in Africa to Influence Investments", id: "tMOrgFdm3L8", category: "africa-dev" },
  { title: "Here's How I Capture All My Creative Ideas", id: "hSGRIz7wHtA", category: "ai" },
  { title: "I Learned Something About Risk Management from My Daughter", id: "0zSvk_dWrUc", category: "inner" },
  { title: "This is An Under-appreciated Investment Opportunity for Those that Want to Invest in Africa", id: "rH-giumfnig", category: "africa-capital" },
  { title: "This is Why More People in the African Diaspora Not Investing in Companies in Africa", id: "pgC8-gvgCok", category: "africa-capital" },
  { title: "This is Why I Believe We Should Stop Worrying About AI as a Creatives", id: "d6Zgir2xoE0", category: "ai" },
  { title: "Here's Why I Don't Set New Year's Resolutions", id: "TkINJQgkzxM", category: "inner" },
  { title: "I Missed Out on 10 Million by Not Making an Investment I Easily Could Have", id: "EuCYDqFUR-Y", category: "money" },
  { title: "This is Why We Should Attempt Things that Seem Impossible", id: "nKI7EvLGIHQ", category: "inner" },
  { title: "Failure is an Inevitable Part of Our Journey", id: "znUy3Z55Cs0", category: "inner" },
  { title: "Challenges like the Energy Crisis in Zambia are opportunities", id: "on_5YQ-sAfw", category: "africa-dev" },
  { title: "The Secret to happiness is to choose happiness", id: "cckoBYs7BHs", category: "inner" },
  { title: "There are 3 types of networkers in business", id: "xGg_dmfc7r4", category: "strategy" },
  { title: "This is my definition of founder investor fit", id: "b27rjriVf5o", category: "strategy" },
  { title: "This is Why Maintaining Relationships with Mentors is Important", id: "16mfIPjj4FU", category: "money" },
  { title: "There's More Than Enough Capital to Solve The World's Problems", id: "C3VICQ5llSw", category: "money" },
  { title: "This is How I Ended Up Working in Venture Capital", id: "-36r5sCa0mM", category: "money" },
  { title: "The Opportunity to Do Business in Africa is Huge", id: "Za13-Y7G1GA", category: "africa-dev" },
  { title: "The Value of Hosting a Conference is Bringing People Together", id: "LIDQ5EOLg2o", category: "money" },
  { title: "This is The Investment Climate in Africa", id: "9agq29tmnVw", category: "africa-capital" },
  { title: "This is The Benefit of Free Trade in Africa", id: "vzVbjh1AFBc", category: "africa-dev" },
  { title: "This is How I Manage My Energy", id: "hufFSggIXd8", category: "inner" },
  { title: "My Framework of AI Impacting Education", id: "2-w5j6M8xgU", category: "ai" },
  { title: "This is How I Manage My Energy", id: "U9phAG5SAJw", category: "inner" },
  { title: "The Three Places I Invest My Money Right Now", id: "QDiASm_F6eM", category: "money" },
  { title: "The Most Valuable Companies in The World Make Money and Impact", id: "W_QT1mcqS1E", category: "money" },
  { title: "AI is Changing The Way We Create", id: "P1yOfAURgUE", category: "ai" },
  { title: "My Framework of AI Impacting Education", id: "kwlZdkKw8jA", category: "ai" },
  { title: "Culture Can Bring More Capital", id: "KQdQPb5c8sc", category: "money" },
  { title: "The Secret of Getting Ahead is Getting Started", id: "C8z8FyUh0Zk", category: "inner" },
  { title: "This is Why I Invest in Africa", id: "CyvAuVEA0Ug", category: "africa-capital" },
  { title: "This is My Creative Process", id: "DjUf8ep9n7U", category: "ai" },
  { title: "This is Why It's Interesting that Elon Musk goes into Government", id: "xAFxvHhf4i8", category: "strategy" },
  { title: "This is How Coaching Changed My Life", id: "vVVWf5W4zA4", category: "money" },
];
