export type PatternVideo = { title: string; id: string };

// Seeded from youtube.com/@Sid-Mofya/shorts via browser console snippet on 2026-06-03.
// To add a new short: prepend { title, id } below (newest first).
// id = the YouTube video ID — the part after /shorts/ or /watch?v=
// e.g. https://www.youtube.com/shorts/abc123XYZ → id: "abc123XYZ"
export const videos: PatternVideo[] = [
  { title: "116    If I had to rebuild from nothing, AI would be my cofounder", id: "v2UlrKdu1rU" },
  { title: "115   What gets you out of bed in the morning  It’s not purpose or pressure  It’s presence", id: "RialwAst8zg" },
  { title: "114   Start with silence  Not because you’re tired, but because it’s where clarity begin", id: "MnB-1i4JDP4" },
  { title: "112   When there’s more time than work, what will you do with yourself", id: "8UqXKxwo5Ug" },
  { title: "113   Play isn’t the opposite of work  It’s the purest form of presence", id: "7wFyFupgyeg" },
  { title: "111   Africa holds the origin story  It may also hold the next chapter", id: "5ri0CAqhS1E" },
  { title: "110   Development isn’t always about going ahead  Sometimes it’s about coming home to yourself", id: "gJLFDgpj6jo" },
  { title: "109   In African culture, to mourn well is to live well", id: "xUAx-NP9Sd0" },
  { title: "108  In a world obsessed with numbers, don’t forget  the real asset is human", id: "wCl4GbGJCkc" },
  { title: "107   Rituals don’t need to be erased  They need to be realigned with the pattern", id: "16mUoT9R1lM" },
  { title: "106  The best ideas don’t always come from you  Sometimes they come through you", id: "LyLENmbO_Ig" },
  { title: "105 The smallest rituals create the deepest bonds", id: "qaSGsr-UY-E" },
  { title: "104 Everyone’s chasing reach  I’m chasing resonance", id: "totjncDGp3I" },
  { title: "103 What if simplicity wasn’t a constraint… but a strategy", id: "WU0EZ1PjW1M" },
  { title: "102 If you're still treating AI like a typing assistant, you're missing the point", id: "pE-KJ0W70oM" },
  { title: "101 Before you hire an agency, ask yourself this ONE question", id: "K118F-DwNk8" },
  { title: "100 Exploring investment in Africa is like making the perfect cup of tea", id: "KWJssVfkN58" },
  { title: "99 Burnout isn't just overwork", id: "TN6LIAOgMi8" },
  { title: "98 Financial freedom isn't just about the end result", id: "B_J5miU3uZA" },
  { title: "97 Unresolved projects can sap our energy", id: "A6UPLeUcE14" },
  { title: "96  Your time is limited, so don't waste it living someone else's life", id: "EG-vKeIOSdk" },
  { title: "95 Rethink the Problem to Solve it", id: "Uv_o93_MMWk" },
  { title: "94 Transform Your Challenges Through a Simplification Strategy", id: "eJSpvC-2BLA" },
  { title: "93 Break Challenges Into Manageable Parts to Solve Them", id: "lOc_dza1lWg" },
  { title: "92 Unlock smarter problem solving by daring to start from scratch", id: "ytBXksd3FVg" },
  { title: "91 The Power Lies in Questioning Our Assumptions", id: "I2XMx-PBQ1A" },
  { title: "90  A river of material flows through us when we share our works and our ideas", id: "QVnUOMIGdLg" },
  { title: "89  The way we do anything is the way we do everything", id: "j92cPSrzWvo" },
  { title: "88  When We Don't Yet Know Where We Are Going, We Don't Wait, We Move Forward In The Dark", id: "gL692HN2Ml4" },
  { title: "87  Sometimes The Mistakes Are What Make A Work Great", id: "fwjsBCiGRdc" },
  { title: "86 Zoom in and obsess, zoom out and observe", id: "fWVxS2izDi8" },
  { title: "85 Investing In Emerging Markets Requires A GOOD Exit Strategy", id: "jyOQ98UBg0Q" },
  { title: "84 Who You Invest With MATTERS Most in Emerging Markets Investing", id: "KXfXmdBf_Jk" },
  { title: "83 Is Your Business Idea a Good Fit for Local Markets", id: "2DJouFw6BCE" },
  { title: "82 Protect Your Profits Mastering Currency Hedging in Emerging Markets", id: "SYCfESWXzHE" },
  { title: "81 What Every Investor Absolutely NEEDS to Know About Emerging Markets", id: "2G8lJcozPr8" },
  { title: "80 - New Investment Structures are Making Investing into Mining Accessible to More Investors", id: "lxj5GynPjXU" },
  { title: "79 - Mining Promises Venture Style Return", id: "CeAKXhYPGKU" },
  { title: "78 - Strategic Investments Flow into Mining and You Can Participate", id: "iRPK_xMOYKE" },
  { title: "77 - This is What We Can Learn from Mining Companies", id: "mfxsqCnB7Po" },
  { title: "76 - We Can Not Have a Tech Future Without Investing into the Right Assets", id: "Gkdou1njfyg" },
  { title: "75 - The Next 20 Years are Critical for Africa's Future", id: "j8jN71JpVf4" },
  { title: "74 - Everyone Wants to Start a Business, Few Build Ones That Last", id: "hv0eOMvdwnk" },
  { title: "73 - Uncovering Smart Money: These Are The Trends in Africa", id: "a0b5KnQouyI" },
  { title: "72 - Entrepreneurship in Africa is The New Gold", id: "U_xD4B41f6Q" },
  { title: "71 - Africa is Rich, But Who Exactly Owns Its Wealth?", id: "oqCY2xWunHg" },
  { title: "70 - There are Three Kinds of Businesses Forming with AI Right Now", id: "diGucTzXCc4" },
  { title: "69 - Let's Spark Innovation in African Agriculture", id: "-OnAgVnVFPM" },
  { title: "68 -  This is Why I'm Investing in Mining in Africa", id: "tpLsg6n99Y4" },
  { title: "67 - Happiness Is Divided Into Two Halves, Accumulating and Letting Go", id: "RL9s08Qn-C4" },
  { title: "66 - This is The Difference Between Internal Performance and External Performance", id: "OzkCOJvTs3Y" },
  { title: "65 - From Grid Instability to Powering Millions: The AIIM Story", id: "fLV5mhQPcu0" },
  { title: "64 - Strategic Investments Pay Back, Ask Norfun About the 60 Million Fertilizer Terminal", id: "5Ry47wgKj0k" },
  { title: "63 - Visa's 200 Million Bet was Genious", id: "RQsB4mhkRqc" },
  { title: "62 - Transforming Waste into Wealth: Let's Learn from Twigga Foods' Revolution", id: "spAqVQgeyCs" },
  { title: "61 - CrossBoundary's Revolutionized The Solar Industry in Africa", id: "--OHQ9OU6do" },
  { title: "60 - Remember, There are Things that Don't Change Even with Technology and AI", id: "fTRATNmZ_vc" },
  { title: "59 - The F-Word is Part of Our Experience", id: "MarZGZuSUjI" },
  { title: "58 - We Have to Embrace Embodied Learning in Our Changing World", id: "dh4-sBqP8qI" },
  { title: "57 - We Have to Relearn When We Move from Digital to AI", id: "qA3I5jUEPSo" },
  { title: "56 - We Need to Unlearn to Work Effectively with AI", id: "hrrnaUVWgFU" },
  { title: "55 - Why You Should Not Just Build Wealth", id: "Uf931DvOMBk" },
  { title: "54 - These are the Two Fastest Ways to Build Your Career or Business", id: "gNnS6q4RxX0" },
  { title: "53 - Money Or Soul Or Both", id: "QvbQshpCUzs" },
  { title: "52 - These are The Two Modes of Creativity that I am  Experiencing", id: "JqTvaxDmts0" },
  { title: "51 - Africa's Future Depends on The Small Miners and Farmers", id: "CsMLhWcZBg4" },
  { title: "50 - Legacy is Left in Other People", id: "vTglsd7tAuY" },
  { title: "49 -  Atomic Essays Make You a Better Communicator", id: "LP_ptnZU_gU" },
  { title: "48 - I Love Dukas", id: "VtESuSjRE00" },
  { title: "47 - The 3 Ways How I Evaluate Business Opportunities as a VC", id: "MHdocHds2RE" },
  { title: "46 -  Investing in Mining in Africa is One of The Lowest Risk Investments You Can Make", id: "RHKr8erfyMk" },
  { title: "45 - Sometimes Value Comes in Tiny, Tiny Packages", id: "XM3BFqJpUag" },
  { title: "44 - Sometimes Value Comes From The Most Unexpected of Places", id: "aqn74flHZys" },
  { title: "43 - There are Two Sides of The Coin When Thinking about African Development", id: "dB71veP87rc" },
  { title: "42 - We Can Learn from Bees about Capital", id: "9GxZi16FubU" },
  { title: "41 -  Here is a Way to Think How Bitcoin Promotes its Value as a Currency", id: "BEcFfhHyNHM" },
  { title: "40 - How I Created a Song Combined with a Story that is Thousands of Years Old", id: "ux0MLPnk-aw" },
  { title: "39 - This is Big Lesson We Can Learn from Kodak", id: "0Xp_2Yu_qrg" },
  { title: "38 - I Don't Think of Africa as 54 Countries", id: "pJq8NpK6PhI" },
  { title: "37 - Do You Choose to Make Money Or Meaning", id: "2q_o_iNZjy0" },
  { title: "36 - These are the Two Things I Learned from Going Home Visiting Zambia", id: "EE1rxuES9Rs" },
  { title: "35 - This is The One Policy I Would Change in Africa to Influence Investments", id: "tMOrgFdm3L8" },
  { title: "34 - Here's How I Capture All My Creative Ideas", id: "hSGRIz7wHtA" },
  { title: "33 - I Learned Something About  Risk Management from My Daughter", id: "0zSvk_dWrUc" },
  { title: "32 -  This is An Under-appreciated Investment Opportunity for Those that Want to Invest in Africa", id: "rH-giumfnig" },
  { title: "31 - This is Why More People in the African Diaspora Not Investing in Companies in Africa", id: "pgC8-gvgCok" },
  { title: "30 - This is Why I Believe We Should Stop Worrying About AI as a Creatives", id: "d6Zgir2xoE0" },
  { title: "29 - Here's Why I Don't Set New Year's Resolutions", id: "TkINJQgkzxM" },
  { title: "28 - I Missed Out on 10 Million by Not Making an Investment I Easily Could Have", id: "EuCYDqFUR-Y" },
  { title: "27 - This is Why We Should Attempt Things that Seem Impossible", id: "nKI7EvLGIHQ" },
  { title: "26 - Failure is an Inevitable Part of Our Journey #shorts", id: "znUy3Z55Cs0" },
  { title: "21 - Challenges like the Energy Crisis in Zambia are opportunities #shorts #AfricaInnovation", id: "on_5YQ-sAfw" },
  { title: "22 - The Secret to happiness is to choose happiness #shorts  #SelfLeadership", id: "cckoBYs7BHs" },
  { title: "23 - There are 3 types of networkers in business #shorts  #NetworkingStrategies", id: "xGg_dmfc7r4" },
  { title: "25 - This is my definition of founder investor fit #shorts #EntrepreneurshipTips #InvestorRelations", id: "b27rjriVf5o" },
  { title: "20 - This is Why Maintaining Relationships with Mentors is Important", id: "16mfIPjj4FU" },
  { title: "19 There's More Than Enough Capital to Solve The World's Problems", id: "C3VICQ5llSw" },
  { title: "18 - This is How I Ended Up Working in Venture Capital", id: "-36r5sCa0mM" },
  { title: "17 - The Opportunity to Do Business in Africa is Huge", id: "Za13-Y7G1GA" },
  { title: "16 - The Value of Hosting a Conference is Bringing People Together", id: "LIDQ5EOLg2o" },
  { title: "15 - This is The Investment Climate in Africa", id: "9agq29tmnVw" },
  { title: "14 - This is The Benefit of Free Trade in Africa", id: "vzVbjh1AFBc" },
  { title: "13 - This is How I Manage My Energy", id: "hufFSggIXd8" },
  { title: "12 - My Framework of AI Impacting Education", id: "2-w5j6M8xgU" },
  { title: "11 - This is How I Manage My Energy", id: "U9phAG5SAJw" },
  { title: "10 - The Three Places I Invest My Money Right Now", id: "QDiASm_F6eM" },
  { title: "09 - The Most Valuable Companies in The World Make Money and Impact", id: "W_QT1mcqS1E" },
  { title: "08 - AI is Changing The Way We Create", id: "P1yOfAURgUE" },
  { title: "07 - My Framework of AI Impacting Education", id: "kwlZdkKw8jA" },
  { title: "06 - Culture Can Bring More Capital", id: "KQdQPb5c8sc" },
  { title: "05 - The Secret of Getting Ahead is Getting Started", id: "C8z8FyUh0Zk" },
  { title: "04 This is Why I Invest in Africa", id: "CyvAuVEA0Ug" },
  { title: "03 - This is My Creative Process", id: "DjUf8ep9n7U" },
  { title: "02 - This is Why It's Interesting that Elon Musk goes into Government", id: "xAFxvHhf4i8" },
  { title: "01 - This is How Coaching Changed My Life", id: "vVVWf5W4zA4" },
];
